// src/components/Chat.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { supabase } from '~/lib/supabaseClient'

const props = defineProps({
  gameId: {
    type: [String, Number],
    required: true
  }
})

const messages = ref([])
const newMessage = ref('')
const errorMsg = ref('')
const loading = ref(true)
const user = ref(null)

let chatSubscription = null

const fetchUser = async () => {
  const { data, error } = await supabase.auth.getUser()
  if (error) {
    errorMsg.value = error.message
  } else {
    user.value = data.user
  }
}

const fetchMessages = async () => {
  loading.value = true
  const { data, error } = await supabase
    .from('chat')
    .select('*')
    .eq('game_id', props.gameId)
    .order('created_at', { ascending: true })
  if (error) {
    errorMsg.value = error.message
  } else {
    messages.value = data
  }
  loading.value = false
}

const sendMessage = async () => {
  if (!newMessage.value.trim()) return
  if (!user.value) {
    errorMsg.value = 'You must be logged in to send messages.'
    return
  }
  const message = newMessage.value.trim()
  newMessage.value = ''
  const { error } = await supabase.from('chat').insert([{ game_id: props.gameId, user_id: user.value.id, content: message }])
  if (error) {
    errorMsg.value = error.message
  }
}

const subscribeToChat = () => {
  chatSubscription = supabase
    .channel('public:chat')
    .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'chat', filter: `game_id=eq.${props.gameId}` }, payload => {
      messages.value.push(payload.new)
    })
    .subscribe()
}

onMounted(async () => {
  await fetchUser()
  await fetchMessages()
  subscribeToChat()
})

onUnmounted(() => {
  if (chatSubscription) supabase.removeChannel(chatSubscription)
})
</script>

<template>
  <div class="border rounded p-4 h-[600px] flex flex-col">
    <h2 class="text-xl font-semibold mb-4">Chat</h2>
    <div class="flex-1 overflow-y-auto mb-4 space-y-2">
      <div v-if="loading" class="text-center">Loading messages...</div>
      <div v-else>
        <div v-for="msg in messages" :key="msg.id" class="p-2 rounded bg-gray-100">
          <strong>{{ msg.user_id }}</strong>: {{ msg.content }}
        </div>
      </div>
    </div>
    <div>
      <input
        v-model="newMessage"
        type="text"
        placeholder="Type your message..."
        class="w-full border rounded px-3 py-2 mb-2"
        @keyup.enter="sendMessage"
      />
      <button @click="sendMessage" class="w-full bg-black text-white py-2 rounded hover:bg-gray-800 transition">
        Send
      </button>
      <div v-if="errorMsg" class="text-red-600 font-semibold mt-2">{{ errorMsg }}</div>
    </div>
  </div>
</template>

// src/components/Chat.tsx
'use client'

import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabaseClient'
import type { User } from '@supabase/supabase-js'
import type { Message } from '@/types'

interface ChatProps {
  gameId: string
}

export default function Chat({ gameId }: ChatProps) {
  const [messages, setMessages] = useState<Message[]>([])
  const [newMessage, setNewMessage] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [user, setUser] = useState<User | null>(null)

  useEffect(() => {
    fetchUser()
    fetchMessages()

    // In development, poll for new messages every 3 seconds
    if (process.env.NODE_ENV === 'development') {
      const interval = setInterval(fetchMessages, 3000)
      return () => clearInterval(interval)
    }
  }, [gameId])

  const fetchUser = async () => {
    try {
      const { data: { user }, error } = await supabase.auth.getUser()
      if (error) throw error
      setUser(user)
    } catch (err: any) {
      setError(err.message)
    }
  }

  const fetchMessages = async () => {
    try {
      const { data, error } = await supabase
        .from('chat')
        .select()
        .eq('game_id', gameId)
        .order('created_at', { ascending: true })

      if (error) {
        setError(error.message)
      } else {
        setMessages(data as Message[])
      }
      setLoading(false)
    } catch (err: any) {
      setError(err.message)
      setLoading(false)
    }
  }

  const sendMessage = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!user || !newMessage.trim()) return

    try {
      const { error } = await supabase
        .from('chat')
        .insert({
          game_id: gameId,
          user_id: user.id,
          content: newMessage.trim()
        })

      if (error) throw error
      setNewMessage('')
      // Fetch messages immediately after sending
      fetchMessages()
    } catch (err: any) {
      setError(err.message)
    }
  }

  if (loading) {
    return <div className="p-4">Loading messages...</div>
  }

  return (
    <div className="border rounded-lg bg-white p-4 h-[600px] flex flex-col">
      <div className="flex-1 overflow-y-auto mb-4 space-y-2">
        {messages.map((message) => (
          <div
            key={message.id}
            className={`p-2 rounded ${
              message.user_id === user?.id
                ? 'bg-black text-white ml-auto'
                : 'bg-gray-100'
            } max-w-[80%]`}
          >
            <p className="text-sm">{message.content}</p>
          </div>
        ))}
      </div>

      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded mb-4">
          {error}
        </div>
      )}

      <form onSubmit={sendMessage} className="flex gap-2">
        <input
          type="text"
          value={newMessage}
          onChange={(e) => setNewMessage(e.target.value)}
          placeholder="Type a message..."
          className="flex-1 px-3 py-2 border rounded"
        />
        <button
          type="submit"
          disabled={!newMessage.trim()}
          className="px-4 py-2 bg-black text-white rounded disabled:opacity-50"
        >
          Send
        </button>
      </form>
    </div>
  )
}
